version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: staging
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.28
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
  - dependency-name: "@types/faker"
    versions:
    - 5.1.5
    - 5.1.6
    - 5.1.7
    - 5.5.0
    - 5.5.1
  - dependency-name: prisma
    versions:
    - 1.34.12
    - 2.15.0
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.1
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.0
    - 1.20.1
    - 1.21.1
    - 1.21.2
    - 1.21.3
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
