---
engines:
 rubocop:
   enabled: true
   exclude_paths:
     - config/engines.yml
 duplication:
   enabled: true
   exclude_paths:
     - config/engines.yml
 metric:
   enabled: true
   exclude_paths:
     - config/engines.yml
 coverage:
   enabled: true
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - 'logs/**'
  - 'benchmarks/**/*'
  - 'dist/**/*'
  - 'coverage/**/*'
  - 'src/generated/**/*'
  - '**/__tests__/**' 
