projects:
  app:
    schemaPath: src/schema.graphql
    includes: [
      "schema.graphql", 
      "prisma.graphql",
      "booking.graphql",
      "queries.graphql",
    ]
    extensions:
      endpoints:
        default: http://localhost:3000
  prisma:
    schemaPath: src/generated/prisma.graphql
    includes: [
      "prisma.graphql", 
      "seed.graphql", 
      "datamodel/types.prisma",
      "datamodel/enums.prisma",
    ]
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
