projects:
  app:
    schemaPath: "./src/schema/schema.graphql"
    includes: [
      "prisma.graphql",
      "schema.graphql", 
      "Mutation.graphql",
      "Query.graphql",
      "Subscription.graphql",
      "Enums.graphql",
    ]
    extensions:
      endpoints:
        default: https://minze-database.herokuapp.com/
  prisma:
    schemaPath: "./src/schema/generated/prisma.graphql"
    includes: [
      "prisma.graphql", 
      "seed.graphql", 
      "datamodel/types.prisma",
      "datamodel/enums.prisma",
    ]
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/schema/generated/prisma.ts
