resources:
  - type: storage.v1.bucket
    name: sls-gcp-dev-1553709513882
  - type: cloudfunctions.v1beta2.function
    name: gcp-dev-app
    properties:
      location: us-central1
      availableMemoryMb: 256
      runtime: nodejs8
      timeout: 60s
      function: http
      sourceArchiveUrl: >-
        gs://sls-gcp-dev-1553709513882/serverless/gcp/dev/1553722474087-2019-03-27T21:34:34.087Z/gcp.zip
      labels: {}
      httpsTrigger:
        url: http
